version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.2.0
    steps:
      - run:
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: randombit/botan"
          command: cd /projects/ishiko/cpp && mkdir randombit && git clone https://github.com/ishiko-third-party/randombit_botan.git botan && cd botan && git checkout 2.19.1 && python3 configure.py --prefix=/projects/ishiko/cpp/randombit/botan --disable-shared-library && make && make install && echo 'export ISHIKO_CPP_THIRD_PARTY_BOTAN="/projects/ishiko/cpp/randombit/botan"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ BasePlatform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/base-platform.git && cd base-platform/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Text"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/text.git && cd text/build/gnumake && make
      - checkout:
          path: /projects/ishiko/cpp/networking
      - run:
          name: "Build: Ishiko/C++ Networking"
          command: cd /projects/ishiko/cpp/networking/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Types"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/types.git && cd types/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Collections"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ FileSystem"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Diff"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/diff.git && cd diff/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Tests"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/test-framework.git && cd test-framework/core/build/gnumake && make
      - run:
          name: "Test: Ishiko/C++ Networking"
          command: cd /projects/ishiko/cpp/networking/tests/build/gnumake && make && ./IshikoNetworkingTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
